version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mymatchlog_mysql
    platform: linux/amd64
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./.db-data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  adminer:
    image: adminer
    container_name: mymatchlog_adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:latest
    container_name: mymatchlog_redis
    restart: always
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']

volumes:
  db-data: {}
