#!/bin/bash

# 프로덕션 서버 환경변수 즉시 수정 스크립트
echo "🔧 프로덕션 서버 환경변수 수정을 시작합니다..."

# SSH 연결 및 환경변수 수정 명령어
echo "📋 EC2 서버에 접속하여 다음 명령어들을 순서대로 실행해주세요:"
echo ""
echo "ssh -i your-key.pem ubuntu@3.37.38.116"
echo ""
echo "cd /opt/mymatchlog"
echo ""
echo "# 현재 환경변수 확인"
echo "sudo docker-compose exec app env | grep DB_"
echo ""
echo "# 컨테이너 중지"
echo "sudo docker-compose down"
echo ""
echo "# docker-compose.yml 파일 백업"
echo "sudo cp docker-compose.yml docker-compose.yml.backup"
echo ""
echo "# docker-compose.yml 파일 수정"
echo "sudo nano docker-compose.yml"
echo ""
echo "# environment 섹션을 다음과 같이 수정:"
echo "environment:"
echo "  - NODE_ENV=production"
echo "  - DB_HOST=\${{ secrets.DB_HOST }}"
echo "  - DB_USER=admin"
echo "  - DB_PASSWORD=\${{ secrets.DB_PASSWORD }}"
echo "  - DB_NAME=mymatchlog_production"
echo "  - DB_PORT=3306"
echo "  - REDIS_HOST=\${{ secrets.REDIS_HOST }}"
echo "  - REDIS_PORT=6379"
echo "  - ACCESS_TOKEN_SECRET_KEY=\${{ secrets.ACCESS_TOKEN_SECRET_KEY }}"
echo "  - REFRESH_TOKEN_SECRET_KEY=\${{ secrets.REFRESH_TOKEN_SECRET_KEY }}"
echo "  - ACCESS_TOKEN_EXPIRES_IN=15m"
echo "  - REFRESH_TOKEN_EXPIRES_IN=7d"
echo "  - AWS_ACCESS_KEY=\${{ secrets.AWS_ACCESS_KEY_ID }}"
echo "  - AWS_SECRET_ACCESS_KEY=\${{ secrets.AWS_SECRET_ACCESS_KEY }}"
echo "  - AWS_S3_REGION=ap-northeast-2"
echo "  - AWS_S3_BUCKET_NAME=your-s3-bucket-name"
echo "  - PORT=3000"
echo ""
echo "# 컨테이너 재시작"
echo "sudo docker-compose up -d"
echo ""
echo "# 애플리케이션 시작 대기"
echo "sleep 30"
echo ""
echo "# 데이터베이스 마이그레이션 실행"
echo "sudo docker-compose exec app npm run migrate"
echo "sudo docker-compose exec app npm run seed"
echo ""
echo "# 연결 테스트"
echo "curl http://localhost:3000/api/teams"
echo "curl http://localhost:3000/api/stadiums"
echo ""
echo "✅ 스크립트 완료. 위 단계들을 순서대로 실행해주세요." 