openapi: 3.0.0
info:
  title: Admin API
  description: 관리자 기능 API
  version: 1.0.0

paths:
  /api/admin/events:
    post:
      summary: 새로운 이벤트를 생성합니다.
      description: |
        관리자가 새로운 이벤트를 생성합니다.
        이벤트 시작/종료 시간, 정원 등의 유효성을 검증합니다.
      tags:
        - Admin
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - description
                - start_at
                - end_at
                - gift
                - capacity
              properties:
                title:
                  type: string
                  example: "LG 트윈스 홈경기 티켓 이벤트"
                description:
                  type: string
                  example: "LG 트윈스 홈경기 티켓을 선착순으로 증정합니다."
                start_at:
                  type: string
                  format: date-time
                  example: "2024-07-21T10:00:00Z"
                end_at:
                  type: string
                  format: date-time
                  example: "2024-07-21T18:00:00Z"
                gift:
                  type: string
                  example: "LG 트윈스 홈경기 티켓 2매"
                capacity:
                  type: integer
                  minimum: 1
                  example: 100
      responses:
        '201':
          description: 이벤트 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      event:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          title:
                            type: string
                            example: "LG 트윈스 홈경기 티켓 이벤트"
                          description:
                            type: string
                            example: "LG 트윈스 홈경기 티켓을 선착순으로 증정합니다."
                          start_at:
                            type: string
                            format: date-time
                            example: "2024-07-21T10:00:00Z"
                          end_at:
                            type: string
                            format: date-time
                            example: "2024-07-21T18:00:00Z"
                          gift:
                            type: string
                            example: "LG 트윈스 홈경기 티켓 2매"
                          capacity:
                            type: integer
                            example: 100
                          participant_count:
                            type: integer
                            example: 0
                          created_at:
                            type: string
                            format: date-time
                            example: "2024-07-20T09:00:00Z"
                          updated_at:
                            type: string
                            format: date-time
                            example: "2024-07-20T09:00:00Z"
                  message:
                    type: string
                    example: "이벤트가 성공적으로 생성되었습니다."
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/admin/events/{id}/participants:
    get:
      summary: 특정 이벤트의 참여자 목록을 조회합니다.
      description: |
        관리자가 특정 이벤트에 참여한 사용자들의 목록을 조회합니다.
        참여 시간 순으로 정렬됩니다.
      tags:
        - Admin
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 이벤트 ID
          example: 1
      responses:
        '200':
          description: 참여자 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      participants:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            user_id:
                              type: integer
                              example: 1
                            event_id:
                              type: integer
                              example: 1
                            status:
                              type: string
                              example: "APPLIED"
                            created_at:
                              type: string
                              format: date-time
                              example: "2024-07-21T10:30:00Z"
                            username:
                              type: string
                              example: "user123"
                            email:
                              type: string
                              example: "user@example.com"
                  message:
                    type: string
                    example: "이벤트 참여자 목록 조회에 성공했습니다."
              examples:
                success:
                  summary: 참여자 목록 조회 성공
                  value:
                    success: true
                    data:
                      participants:
                        - id: 1
                          user_id: 1
                          event_id: 1
                          status: "APPLIED"
                          created_at: "2024-07-21T10:30:00Z"
                          username: "user123"
                          email: "user@example.com"
                        - id: 2
                          user_id: 2
                          event_id: 1
                          status: "APPLIED"
                          created_at: "2024-07-21T10:35:00Z"
                          username: "user456"
                          email: "user456@example.com"
                    message: "이벤트 참여자 목록 조회에 성공했습니다."
                empty:
                  summary: 참여자 없음
                  value:
                    success: true
                    data:
                      participants: []
                    message: "이벤트 참여자 목록 조회에 성공했습니다."
        '404':
          description: 이벤트를 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              example: "ADMIN_MISSING_REQUIRED_FIELDS"
            message:
              type: string
              example: "모든 필수 필드를 입력해주세요."
        timestamp:
          type: string
          format: date-time
          example: "2024-07-21T10:30:00Z"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 