paths:
  /api/match-logs:
    get:
      tags:
        - Match Logs
      summary: 내 직관 기록 목록 조회
      description: 현재 로그인된 사용자의 직관 기록 목록을 페이지네이션과 함께 조회합니다.
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: "페이지 번호 (기본값: 1)"
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: "한 페이지당 항목 수 (기본값: 10, 최대: 100)"
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: 직관 기록 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      matchLogs:
                        type: array
                        items:
                          $ref: '#/components/schemas/MatchLogListItem'
                      pagination:
                        $ref: '#/components/schemas/Pagination'
                  message:
                    type: string
                    example: "직관 기록 목록 조회에 성공했습니다."
        '401':
          description: 인증 실패
    post:
      tags:
        - Match Logs
      summary: 직관 기록 생성
      description: 새로운 직관 기록을 생성합니다.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMatchLogRequest'
      responses:
        '201':
          description: 직관 기록 생성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      matchLogId:
                        type: integer
                        example: 1
                  message:
                    type: string
                    example: "직관 기록이 성공적으로 등록되었습니다."
        '400':
          description: 잘못된 입력값
        '401':
          description: 인증 실패

  /api/match-logs/{id}:
    get:
      tags:
        - Match Logs
      summary: 직관 기록 상세 조회
      description: 특정 직관 기록의 상세 정보를 조회합니다. 본인의 기록만 조회 가능합니다.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: 직관 기록 ID
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: 직관 기록 상세 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      matchLog:
                        $ref: '#/components/schemas/MatchLogDetail'
                  message:
                    type: string
                    example: "직관 기록 상세 조회에 성공했습니다."
        '401':
          description: 인증 실패
        '403':
          description: 접근 권한 없음
        '404':
          description: 직관 기록을 찾을 수 없음
    patch:
      tags:
        - Match Logs
      summary: 직관 기록 수정
      description: 기존 직관 기록을 수정합니다. 본인의 기록만 수정 가능합니다.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: 직관 기록 ID
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMatchLogRequest'
      responses:
        '200':
          description: 직관 기록 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      matchLog:
                        $ref: '#/components/schemas/MatchLogDetail'
                  message:
                    type: string
                    example: "직관 기록이 성공적으로 수정되었습니다."
        '400':
          description: 잘못된 입력값
        '401':
          description: 인증 실패
        '403':
          description: 수정 권한 없음
        '404':
          description: 직관 기록을 찾을 수 없음
    delete:
      tags:
        - Match Logs
      summary: 직관 기록 삭제
      description: 기존 직관 기록을 삭제합니다. 본인의 기록만 삭제 가능합니다.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: 직관 기록 ID
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: 직관 기록 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    example: {}
                  message:
                    type: string
                    example: "직관 기록이 성공적으로 삭제되었습니다."
        '401':
          description: 인증 실패
        '403':
          description: 삭제 권한 없음
        '404':
          description: 직관 기록을 찾을 수 없음

 