paths:
  /api/stadiums:
    get:
      tags:
        - Stadiums
      summary: 경기장 목록 조회
      description: 모든 경기장 목록을 조회합니다.
      responses:
        '200':
          description: 경기장 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      stadiums:
                        type: array
                        items:
                          $ref: '#/components/schemas/Stadium'
                  message:
                    type: string
                    example: "경기장 목록 조회에 성공했습니다."

  /api/stadiums/{id}:
    get:
      tags:
        - Stadiums
      summary: 경기장 상세 조회
      description: 특정 경기장의 상세 정보를 조회합니다.
      parameters:
        - name: id
          in: path
          required: true
          description: 경기장 ID
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: 경기장 상세 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      stadium:
                        $ref: '#/components/schemas/Stadium'
                  message:
                    type: string
                    example: "경기장 조회에 성공했습니다."
        '404':
          description: 경기장을 찾을 수 없음 