paths:
  /api/teams:
    get:
      tags:
        - Teams
      summary: 팀 목록 조회
      description: KBO 리그의 모든 팀 목록을 조회합니다. 사용자가 응원팀을 선택할 때 사용됩니다.
      responses:
        '200':
          description: 팀 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      teams:
                        type: array
                        items:
                          $ref: '#/components/schemas/Team'
                  message:
                    type: string
                    example: "팀 목록 조회에 성공했습니다."

components:
  schemas:
    Team:
      type: object
      properties:
        id:
          type: integer
          description: 팀 고유 ID
          example: 1
        name:
          type: string
          description: 팀 이름
          example: "LG 트윈스"
        logo_url:
          type: string
          nullable: true
          description: 팀 로고 이미지 URL
          example: "https://example.com/lg-logo.png"
        home_stadium:
          type: string
          description: 홈구장 이름
          example: "서울종합운동장 야구장" 